@URL=http://localhost/Sobjucas

### Obter todas as categorias
GET {{URL}}/back-end/api/category/get.php

@cat = 3;

### Oter uma categoria
GET {{URL}}/back-end/api/category/getOne.php?id={{cat}}

### Atualizar categoria
POST {{URL}}/back-end/api/category/update.php?id=2
Content-Type: application/json

{
  "nome": "lolo",
  "descricao": "violao bonito"
}

### Criar uma categoria
POST {{URL}}/back-end/api/category/create.php
Content-Type: application/json

{
  "nome": "Percurssao",
  "descricao": "instrumentos de percussao, batuques, ritmo"
}
  


### Deletar uma categoria
GET {{URL}}/api/category/delete.php?id=2