@URL=http://localhost/Sobjucas/back-end

@JWT-admin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIn0.gpFe96SqBlPONuca_ZIkct53feYmYvdOhkRRwuIogZQ
@JWT-user = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6Ik1hdGV1cyIsInJvbGUiOiJ1c2VyIn0.0NJB8O2KHEphu1C8Lsw-WrJb5g-7VMeMZ1r7mv0eKb4
### Obter todos os produtos
GET {{URL}}/api/product/get.php
Authorization: {{JWT-user}}



### Atualizar produtos
POST {{URL}}/api/product/update.php?id=4
Content-Type: application/json

{
  "nome": "lolo",
  "descricao": "violao bonito",
  "id_categoria": 1,
  "preco": "1250,00",
  "quantidade": 3
}

### Criar um produto
POST {{URL}}/api/product/create.php
Content-Type: application/json
//Authorization: {{JWT-user}}

{
  "nome": "buceta",
  "descricao": "violao bonito",
  "id_categoria": 3,
  "preco": "1250,00",
  "quantidade": 3
}


### Deletar um produto
GET {{URL}}/back-end/api/product/delete.php?id=2