@URL=http://localhost/Sobjucas

### Obter todas as compras
GET {{URL}}/api/product-purchase/get.php



### Atualizar compras
POST {{URL}}/api/product-purchase/update.php?id_compra=1&id_produto=2
Content-Type: application/json

{
  "id_compra": 1,
  "id_produto": 2,
  "quantidade": 8
}

### Criar uma compra
POST {{URL}}/api/product-purchase/create.php
Content-Type: application/json

{
  "id_compra": 3,
  "id_produto": 2,
  "quantidade": 5
}


### Deletar uma compra
GET {{URL}}/api/product-purchase/delete.php?id_compra=null&id_produto=2