@URL=http://localhost/Sobjucas

### Obter todos os produtos
GET {{URL}}/api/product/get.php



### Atualizar produtos
POST {{URL}}/api/product/update.php?id=4
Content-Type: application/json

{
  "nome": "lolo",
  "descricao": "violao bonito",
  "id_categoria": 1,
  "preco": "1250,00",
  "quantidade": 3
}

### Criar um produto
POST {{URL}}/api/product/create.php
Content-Type: application/json

{
  "nome": "Violao",
  "descricao": "violao bonito",
  "id_categoria": 1,
  "preco": "1250,00",
  "quantidade": 3
}


### Deletar um produto
GET {{URL}}/api/product/delete.php?id=2