@URL=http://localhost/Sobjucas

### Obter todas as compras
GET {{URL}}/api/purchase/get.php



### Atualizar compras
POST {{URL}}/api/purchase/update.php?compra_id=1
Content-Type: application/json

{
  "id_usuario": 1,
  "valor": "742.00",
  "data_compra": "2021-05-15",
  "itens": [
    {
      "id_produto": 1,
      "quantidade": 1
    },
    {
      "id_produto": 2,
      "quantidade": 4
    }
  ]
}

### Criar uma compra
POST {{URL}}/api/purchase/create.php
Content-Type: application/json

{
  "id_usuario": 1,
  "valor": "742.00",
  "data_compra": "2021-05-15"
}


### Deletar uma compra
GET {{URL}}/api/purchase/delete.php?id=2